### ISSUE TITLE
Missing "example-image-a"

### ISSUE THREAD

**Issue by kubouch** [tvalimaki/beamertheme-tuni#3] opened 2019-04-25 09:10 UTC
When compiling the example (`make all`), the compilation throws an error about the image `example-image-a` not found. It would help to include the example image with the repository.

**Comment by tvalimaki** [comment] 2019-04-29 07:30
`example-image-a` is part of the `mwe` package. You need to have the package on your system in order to compile. I'm closing this, as it's essentially a duplicate of #5.

**Closed as completed by tvalimaki** 2019-04-29 07:30 UTC
